import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
    #"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"
#
[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"
#
[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

