import = [
    "~/.config/alacritty/themes/themes/dracula.toml",
    #"~/.config/alacritty/themes/themes/catppuccin_latte.toml"
    #"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
    #"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"
#
[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"
#
[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "none"
# use Option/Alt as Meta key for OSx
# The Both value is referring to treating both left and right option keys as alt.
option_as_alt = 'Both'

#[cursor.style]
#shape = "Underline"
#blinking = "On"

[cursor.vi_mode_style]
shape = "Underline"
blinking = "On"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true

[window.padding]
x = 7
y = 0

[env]
TERM = "xterm-256color"
