format = """
$directory\
$git_branch\
$git_status\
$terraform\
$character"""

#[fill]
#symbol = ' '

[terraform]
format = '[TF $workspace]($style) '


[git_status]
conflicted = 'conflict'
ahead = 'ahead'
behind = 'behind'
diverged = 'diverged'
#up_to_date = 'âœ“'
untracked = '*'
stashed = ''
modified = '*'
staged = '[++\($count\)](green)'
renamed = 'renamed'
deleted = 'deleted'
